/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UpRouteImport } from './routes/up'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinWorkspaceRouteImport } from './routes/join-workspace'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppSettingsWorkspaceRouteImport } from './routes/app/settings/workspace'
import { Route as AppSettingsServiceZonesRouteImport } from './routes/app/settings/service-zones'
import { Route as AppSettingsPeopleRouteImport } from './routes/app/settings/people'
import { Route as AppSettingsNotificationsRouteImport } from './routes/app/settings/notifications'
import { Route as AppSettingsLabelsRouteImport } from './routes/app/settings/labels'
import { Route as AppSettingsAccountRouteImport } from './routes/app/settings/account'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UpRoute = UpRouteImport.update({
  id: '/up',
  path: '/up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinWorkspaceRoute = JoinWorkspaceRouteImport.update({
  id: '/join-workspace',
  path: '/join-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsWorkspaceRoute = AppSettingsWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsServiceZonesRoute = AppSettingsServiceZonesRouteImport.update({
  id: '/service-zones',
  path: '/service-zones',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPeopleRoute = AppSettingsPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsLabelsRoute = AppSettingsLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/join-workspace': typeof JoinWorkspaceRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/up': typeof UpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/labels': typeof AppSettingsLabelsRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/people': typeof AppSettingsPeopleRoute
  '/app/settings/service-zones': typeof AppSettingsServiceZonesRoute
  '/app/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join-workspace': typeof JoinWorkspaceRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/up': typeof UpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app': typeof AppIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/labels': typeof AppSettingsLabelsRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/people': typeof AppSettingsPeopleRoute
  '/app/settings/service-zones': typeof AppSettingsServiceZonesRoute
  '/app/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/app/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/join-workspace': typeof JoinWorkspaceRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/up': typeof UpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/labels': typeof AppSettingsLabelsRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/people': typeof AppSettingsPeopleRoute
  '/app/settings/service-zones': typeof AppSettingsServiceZonesRoute
  '/app/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/join-workspace'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/up'
    | '/verify-email'
    | '/app/settings'
    | '/app/'
    | '/onboarding/'
    | '/app/settings/account'
    | '/app/settings/labels'
    | '/app/settings/notifications'
    | '/app/settings/people'
    | '/app/settings/service-zones'
    | '/app/settings/workspace'
    | '/app/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/join-workspace'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/up'
    | '/verify-email'
    | '/app'
    | '/onboarding'
    | '/app/settings/account'
    | '/app/settings/labels'
    | '/app/settings/notifications'
    | '/app/settings/people'
    | '/app/settings/service-zones'
    | '/app/settings/workspace'
    | '/app/settings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/join-workspace'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/up'
    | '/verify-email'
    | '/app/settings'
    | '/app/'
    | '/onboarding/'
    | '/app/settings/account'
    | '/app/settings/labels'
    | '/app/settings/notifications'
    | '/app/settings/people'
    | '/app/settings/service-zones'
    | '/app/settings/workspace'
    | '/app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JoinWorkspaceRoute: typeof JoinWorkspaceRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  UpRoute: typeof UpRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/up': {
      id: '/up'
      path: '/up'
      fullPath: '/up'
      preLoaderRoute: typeof UpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-workspace': {
      id: '/join-workspace'
      path: '/join-workspace'
      fullPath: '/join-workspace'
      preLoaderRoute: typeof JoinWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/workspace': {
      id: '/app/settings/workspace'
      path: '/workspace'
      fullPath: '/app/settings/workspace'
      preLoaderRoute: typeof AppSettingsWorkspaceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/service-zones': {
      id: '/app/settings/service-zones'
      path: '/service-zones'
      fullPath: '/app/settings/service-zones'
      preLoaderRoute: typeof AppSettingsServiceZonesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/people': {
      id: '/app/settings/people'
      path: '/people'
      fullPath: '/app/settings/people'
      preLoaderRoute: typeof AppSettingsPeopleRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/notifications': {
      id: '/app/settings/notifications'
      path: '/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/labels': {
      id: '/app/settings/labels'
      path: '/labels'
      fullPath: '/app/settings/labels'
      preLoaderRoute: typeof AppSettingsLabelsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/account': {
      id: '/app/settings/account'
      path: '/account'
      fullPath: '/app/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsLabelsRoute: typeof AppSettingsLabelsRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsPeopleRoute: typeof AppSettingsPeopleRoute
  AppSettingsServiceZonesRoute: typeof AppSettingsServiceZonesRoute
  AppSettingsWorkspaceRoute: typeof AppSettingsWorkspaceRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsLabelsRoute: AppSettingsLabelsRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsPeopleRoute: AppSettingsPeopleRoute,
  AppSettingsServiceZonesRoute: AppSettingsServiceZonesRoute,
  AppSettingsWorkspaceRoute: AppSettingsWorkspaceRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingRouteChildren {
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JoinWorkspaceRoute: JoinWorkspaceRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  UpRoute: UpRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
