import { defineConfig } from "tsdown"

export default defineConfig({
  clean: true,
  copy: [
    {
      from: "src/styles/globals.css",
      rename: "globals.css",
    },
  ],
  deps: {
    skipNodeModulesBundle: true,
  },
  dts: true,
  entry: {
    "components/accordion": "src/components/accordion.tsx",
    "components/alert": "src/components/alert.tsx",
    "components/alert-dialog": "src/components/alert-dialog.tsx",
    "components/aspect-ratio": "src/components/aspect-ratio.tsx",
    "components/avatar": "src/components/avatar.tsx",
    "components/badge": "src/components/badge.tsx",
    "components/breadcrumb": "src/components/breadcrumb.tsx",
    "components/button": "src/components/button-entry.ts",
    "components/button-group": "src/components/button-group.tsx",
    "components/calendar": "src/components/calendar.tsx",
    "components/card": "src/components/card.tsx",
    "components/carousel": "src/components/carousel.tsx",
    "components/chart": "src/components/chart.tsx",
    "components/checkbox": "src/components/checkbox.tsx",
    "components/collapsible": "src/components/collapsible.tsx",
    "components/combobox": "src/components/combobox.tsx",
    "components/command": "src/components/command.tsx",
    "components/context-menu": "src/components/context-menu.tsx",
    "components/dialog": "src/components/dialog.tsx",
    "components/direction": "src/components/direction.tsx",
    "components/drawer": "src/components/drawer.tsx",
    "components/dropdown-menu": "src/components/dropdown-menu.tsx",
    "components/empty": "src/components/empty.tsx",
    "components/field": "src/components/field.tsx",
    "components/hover-card": "src/components/hover-card.tsx",
    "components/input": "src/components/input.tsx",
    "components/input-group": "src/components/input-group.tsx",
    "components/input-otp": "src/components/input-otp.tsx",
    "components/item": "src/components/item.tsx",
    "components/kbd": "src/components/kbd.tsx",
    "components/label": "src/components/label.tsx",
    "components/menubar": "src/components/menubar.tsx",
    "components/native-select": "src/components/native-select.tsx",
    "components/navigation-menu": "src/components/navigation-menu.tsx",
    "components/pagination": "src/components/pagination.tsx",
    "components/popover": "src/components/popover.tsx",
    "components/progress": "src/components/progress.tsx",
    "components/radio-group": "src/components/radio-group.tsx",
    "components/resizable": "src/components/resizable.tsx",
    "components/scroll-area": "src/components/scroll-area.tsx",
    "components/select": "src/components/select.tsx",
    "components/separator": "src/components/separator.tsx",
    "components/sheet": "src/components/sheet.tsx",
    "components/sidebar": "src/components/sidebar.tsx",
    "components/skeleton": "src/components/skeleton.tsx",
    "components/slider": "src/components/slider.tsx",
    "components/sonner": "src/components/sonner.tsx",
    "components/spinner": "src/components/spinner.tsx",
    "components/switch": "src/components/switch.tsx",
    "components/table": "src/components/table.tsx",
    "components/tabs": "src/components/tabs.tsx",
    "components/textarea": "src/components/textarea.tsx",
    "components/toggle": "src/components/toggle.tsx",
    "components/toggle-group": "src/components/toggle-group.tsx",
    "components/tooltip": "src/components/tooltip.tsx",
    index: "src/index.ts",
  },
  format: "esm",
  hash: false,
  outDir: "dist",
  platform: "neutral",
})
